sudo: false

language: node_js
node_js:
  - "6"

cache:
  directories:
    $HOME/.npm
    $HOME/.cache # Includes bower cache

before_install:
  # Prevent the npm loading indicator
  - npm config --global set spin false
  # If npm version is less 3.0.0 upgrade to 3
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi

install:
  - npm install --no-optional

script: npm test
